[package]
name = "pipes"
version = "0.1.0"
authors = ["ethan"]
build = "build.rs"

[dependencies]
libc = "0.2"
rand = "0.3.15"
num = "0.1"
lazy_static = "0.2.2"
stainless = "*"

[build-dependencies]
gcc = "0.3"
